server:
  port: 8000

  tomcat:
    accept-count: 6000
    threads:
      max: 800
      min-spare: 100
    accesslog:
      enabled: true
      directory: E:/tomcat
      pattern: '%h %l %u %t "%r" %s %b %D'
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-headers: "*"
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allow-credentials: true
