server:
  port: 8000

  tomcat:
    accept-count: 6000
    threads:
      max: 800
      min-spare: 100
    accesslog:
      enabled: true
      directory: E:/tomcat
      pattern: '%h %l %u %t "%r" %s %b %D'
spring:
  main:
    web-application-type: reactive
  data:
    redis:
      database: 0 # Redis 数据库索引（默认为 0）
      host: 127.0.0.1 # Redis 服务器地址
      port: 6379 # Redis 服务器连接端口
      timeout: 5s # 读超时时间
      connect-timeout: 5s # 链接超时时间
      lettuce:
        pool:
          max-active: 200 # 连接池最大连接数
          max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接
          max-idle: 10 # 连接池中的最大空闲连接
  cloud:
    sentinel:
      transport:
        port: 8702
        dashboard: localhost:8888
      web-context-unify: false
      eager: true
    gateway:
      discovery:
        locator:
          enabled: true
          route-id-prefix: gateway-
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-headers: "*"
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allow-credentials: true