server:
  port: 8081

#spring:
#  data:
#    redis:
#      database: 1
#      host: 127.0.0.1
#      port: 6379
#      timeout: 10s
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/another_domain
#    username: root
#    password: ${database.password}
#  mail:
#    host: ${email.host}
#    port: ${email.port}
#    username: ${email.username}
#    password: ${email.password}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          enable: true
#          ssl:
#            enable: true
#          socketFactoryClass: javax.net.ssl.SSLSocketFactory
#      default-encoding: UTF-8
jimmer:
  language: kotlin
  show-sql: true
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  pretty-sql: true
#sa-token:
#  token-name: Authorization
#  timeout: 604800
#  token-style: simple-uuid
dubbo:
  application:
    name: auth
    version: 1.0
    qos-port: 22223
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: -1
rate:
  limit:
    local:
      enabled: true
      default:
        permitsPerSecond: 1
        timeout: 0
      concurrent:
        enabled: true
        default:
          corePoolSize: 1
          maximumPoolSize: 1
          keepAliveTime: 30
          queueCapacity: 1
          timeout: 1
